load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "lista-simples",
    hdrs = ["listasimples.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "lista-dupla",
    hdrs = ["listadupla.h"],
    visibility = ["//visibility:public"],
)